apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeapps-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: kubeapp.54.228.87.23.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubeapps 
            port:
              number: 80
