{{ if .Values.ingress.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-ingress
  labels:
  {{- include "spring.labels" . | nindent 4}}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 80
{{- end -}}
{{ end }}
