kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service #from RELEASE NAME
spec:
  selector:
    app: music
    {{- include "spring.labels" . | nindent 4 }}
  type: {{ .Values.service.type }} #from values
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
