apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment #from RELEASE NAME
spec:
  selector:
    matchLabels:
      app: music
  replicas: {{ .Values.deployment.replicaNum }} #from values
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Values.container.name }} #from values
        image: {{ .Values.container.image }} #from values
        ports:
        - containerPort: 8080
