apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2 
  template: 
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: spring-music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
